channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=21.0.1
  - asdf=2.13.0
  - asdf-astropy=0.2.2
  - astropy=5.1
  - astroquery=0.4.6
  - gala=1.6.1
  - numpy=1.22
  - palettable=3.3.0
  - tqdm=4.64
  - pip:
      - galpy==1.8.2
      - galstreams==1.0.3
      - matplotlib==3.7.1
      - trackstream@git+https://github.com/nstarman/trackstream.git
