[tool.black]
line-length = 120


[tool.isort]
profile = "black"
line_length = 120
skip_glob = [".snakemake/*"]
sections=["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
import_heading_stdlib="STDLIB"
import_heading_thirdparty="THIRD-PARTY"
import_heading_firstparty="FIRST-PARTY"
import_heading_localfolder="LOCAL"
known_first_party = ["trackstream"]
known_localfolder = ["paths", "conf"]

[tool.ruff]
target-version = "py310"
line-length = 120
select = ["ALL"]
ignore = [
    "B008",  # do not perform function calls in argument defaults
    # pydocstyle (D)
    "D203",  # one-blank-line-before-class  # contra numpydoc
    "D213",  # multi-line-summary-second-line
]

[tool.ruff.per-file-ignores]
"src/scripts/conf.py" = ["INP001"]
