"""Configuration."""

import numpy as np
import paths
from astropy.table import QTable

##############################################################################
# CODE
##############################################################################

tbl = QTable.read(paths.data / "gd1-with-masks.fits")
tbl = tbl[tbl["pm_mask"] & tbl["gi_cmd_mask"] & tbl["stream_track_mask"]]

# fmt: off
tbl["thin_stream_sel"] = np.array(
    [
        False, True, False, False, False, False, False, False, False, False, False, True, False, False, False, False,
        False, False, False, False, True, True, False, True, False, False, False, False, True, False, False, False,
        False, False, False, True, False, True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, False, True, False, True, True, True, False, False, False, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False,
        False, False, False, True, False, False, False, True, True, False, False, False, False, False, True, True,
        False, False, False, False, False, False, True, False, False, True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
        True, True, True, True, True, True, True, False, True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, True, False, True, True, False, False, True,
        False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
        False, True, True, True, True, False, True, True, False, False, True, False, True, True, False, True, True,
        True, False, False, True, True, False, True, True, True, False, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True,
        False, True, True, True, True, False, False, False, False, False, False, True, True, True, True, False,
        True, True, True, False, True, True, True, True, True, True, True, True, True, False, True, True, True,
        True, True, True, True, True, True, True, True, False, True, True, True, False, True, True, True, True,
        True, True, True, False, True, False, False, True, False, True, False, True, True, True, False, False, True,
        True, False, True, True, False, False, False, False, False, True, True, True, True, True, True, True, True,
        True, False, True, True, True, False, True, True, True, True, False, True, False, False, True, False, False,
        True, False, True, False, False, False, True, False, False, True, True, False, True, True, True, True,
        False, False, False, True, False, True, True, False, True, False, True, True, False, False, True, True,
        True, False, True, True, False, True, False, True, False, True, False, True, False, False, False, False,
        False, True, True, False, False, False, True, True, False, True, False, False, True, True, True, False,
        False, True, False, False, False, False, False, False, False, False, False, False, True, True, False, False,
        False, True, False, True, True, True, False, True, True, True, True, True, True, False, True, True, True,
        True, True, True, True, True, False, False, True, True, True, False, True, True, True, True, True, True,
        True, False, True, True, True, True, True, False, False, False, False, False, True, False, False, True,
        False, False, False, False, False, False, False, False, False, False, False, False, False, True, True,
        False, False, True, False, True, True, True, True, True, True, True, True, True, True, True, False, True,
        True, True, True, True, True, True, True, True, False, True, True, True, True, True, False, True, True,
        True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True,
        True, True, True, True, True, False, True, True, True, True, False, True, True, True, True, False, True,
        True, False, True, True, True, True, True, True, True, True, True, True, False, True, False, True, False,
        True, False, False, False, True, False, False, False, True, True, True, True, False, True, False, True,
        True, False, True, False, False, True, True, False, False, True, False, False, False, True, False, False,
        False, False, True, True, True, False, False, False, True, False, False, True, False, True, True, True,
        True, True, True, True, True, True, False, False, True, True, True, True, False, True, True, False, True,
        True, True, False, True, True, True, True, True, True, False, True, True, False, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True,
        True, True, True, False, True, True, True, False, True, True, True, True, True, True, True, True, True,
        True, False, False, False, True, True, True, False, True, False, True, False, False, True, False, False,
        True, True, False, True, False, False, True, True, False, False, False, False, False, False, False, False,
        True, True, False, True, True, True, True, False, True, True, True, True, True, True, False, True, True,
        False, True, False, False, False, False, False, False, False, False, False, False, False, True, True, True,
        False, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False,
        False, False, True, False, True, False, False, True, True, True, False, True, True, True, True, False, True,
        True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True,
        False, True, True, True, True, True, True, False, True, True, False, False, False, True, True, False, True,
        False, False, False, True, False, True, False, True, True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, True, True, False, True, True, True, True, True,
        True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, False, True, True, True, True, True, True, True, False, True, True, True, True, True,
        True, True, True, True, True, False, True, False, True, True, True, True, True, True, True, False, True,
        True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, True, False,
        False, False, False, False, True, False, False, False, False, False, True, False, False, True, True, True,
        False, False, False, False, False, False, False, False, False, False, False, False, False, False, True,
        False, False, True, False, True, True, True, False, True, True, True, True, True, True, True, False, True,
        True, True, True, True, True, True, True, True, False, True, True, True, False, True, True, True, True,
        True, False, False, True, True, True, True, False, True, True, False, False, False, True, False, False,
        False, False, False, True, False, False, False, False, True, True, False, False, False, False, True, False,
        True, False, False, False, False, False, False, True, False, False, True, True, True, True, True, False,
        False, False, False, False, False, False, True, True, True, True, True, False, True, True, False, True,
        True, True, False, True, True, True, True, True, True, True, True, True, False, True, True, False, True,
        False, True, False, False, False, True, False, False, False, False, False, False, False, False, True, True,
        True, True, True, True, True, True, False, False, False, True, True, False, False, False, False, False,
        False, True, False, True, False, False, True, True, False, False, True, False, False, False, False, False,
        False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, False, False, False, False, True, False, False, True, False, False, False, False,
        False, False, True, False, False, False, False, True, False, False, True, True, True, True, False, True,
        True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True,
        True, True, True, False, False, False, False, False, False, False, False, False, True, True, True, True,
        True, True, False, True, True, True, False, False, False, True, True, True, False, False, True, True, True,
        True, True, False, False, False, True, True, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, True, False, False, False, False, True, True, False, False, False, True,
        True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, False, False, False, False, True, True, True,
        False, False, False, True, False, False, False, False, False, True, False, False, False, False, False,
        False, False, False, False, True, True, True, False, False, True, True, False, True, False, True, False,
        True, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
        True, False, False, False, True, True, True, True, True, True, True, False, True, True, True, True, True,
        True, True, True, False, False, True, True, False, False, True, True, True, True, True, True, False, True,
        True, False, True, False, False, True, False, True, False, False, False, True, False, True, False, True,
        True, True, True, True, False, True, True, True, False, True, True, False, False, True, True, True, True,
        True, True, True, True, False, True, False, True, False, True, False, True, True, True, True, True, False,
        True, True, True, True, True, False, True, True, True, True, False, False, False, False, True, False, False,
        False, True, True, True, True, True, True, False, True, True, True, True, True, True, False, True, True,
        True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, False, True,
        True, True, True, True, False, False, False, True, True, True, False, True, False, False, True, True, False,
        False, False, True, False, False, True, True, True, True, True, False, False, True, False, True, True,
        False, False, True, True, False, True, True, True, False, True, True, False, False, False, False, False,
        False, True, False, False, True, True, True, True, True, True, True, False, False, True, True, True, True,
        True, False, True, True, False, True, True, False, True, True, True, False, True, True, True, True, True,
        True, True, True, False, True, False, False, True, True, True, True, False, True, False, True, True, True,
        True, True, True, False, True, True, True, True, True, False, True, False, True, True, False, True, True,
        True, True, False, False, True, False, False, False, False, False, False, True, False, False, True, True,
        True, True, False, True, False, False, True, False, False, False, True, False, False, False, True, True,
        False, True, False, False, False, True, True, False, False, True, True, False, False, True, False, True,
        False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
        False, False, False, True, False, True, False, False, True, True, False, True, True, True, False, True,
        True, True, False, False, False, True, False, True, False, True, True, True, True, False, True, True, True,
        True, True, True, True, False, False, True, True, True, True, True, False, True, True, True, True, True,
        False, False, True, False, False, True, False, True, True, True, False, False, True, True, False, True,
        True, False, False, False, False, False, False, False, False, True, False, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, False, False,
        True, True, True, True, True, True, True, False, True, True, True, True, True, False, True, False, True,
        True, True, True, True, True, True, True, True, False, True, True, True, True, False, True, True, True,
        False, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True,
        True, True, False, True, True, True, True, False, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False,
        False, False, False, False, False, False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, True, True, True, True, False, True, False, False, True,
        True, True, True, False, True, False, True, True, False, True, True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False, True, False, False, True, False,
        False, True, True, False, False, True, True, True, True, False, False, False, True, True, False, False,
        True, False, False, True, True, False, True, False, True, True, True, False, True, True, False, False,
        False, False, False, False, False,
    ],
)
# fmt: on

# Save
tbl.write(paths.data / "PWB18_thinsel.ecsv", overwrite=True)
